version: '3'

services:
  redis:
    image: "redis:alpine"
  database:
    container_name: vacation_me_database_server
    image: vacation_me_database
    build: database/
  details:
    container_name: vacation_me_details_server
    image: vacation_me_details
    build: .
    environment:
      PGHOST: postgres
      PGUSER: marcelinoornelas
      PGDATABASE: vacation_me
      # PGPASSWORD: 
      # NEW_RELIC_KEY:
      REDIS_URI: redis
    depends_on:
      - "database"
      - "redis"
    links:
      - redis
      - database
    ports:
      - "80:3001"
    # command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]

# version: "2"
# services:
#   airfec:
#     container_name: airfec_photos_server
#     build: .
#     image: airfec_photos
#     ports:
#       - '80:3000'
#     environment:
#       - MONGODB_URI=mongo_server
#       - PORT=3000
#     depends_on:
#       - 'database'
#     links: 
#       - database:mongo_server
#   database:
#     container_name: mongo
#     image: mongo:latest